# PostgreSQL. Versions 7.4 and 8.x are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

common: &common
  adapter: postgresql
  encoding: unicode
  database: kingarturius
  pool: 5
  username: king
  password: kingpass

  host: localhost
  port: 5432

development:
  <<: *common

test:
  adapter: postgresql
  encoding: unicode
  database: kingarturius_test
  pool: 5
  username: king
  password: kingpass

production:
  <<: *common
